# Check that there is correct spelling in all files
name: Check spelling

on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 16 * *"


jobs:
  check_spelling:

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:

      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Remove folders that must not be spellchecked
        run: |
          rm -rf docs/evaluations
          rm docs/meeting_notes/older.md
          rm docs/meeting_notes/20230913.md
          rm docs/meeting_notes/20231020.md
          rm docs/meeting_notes/20230920.md
          rm docs/meeting_notes/2022_autumn.md
          rm -rf development_design
          rm -rf projects
          rm -rf docs/feedback
          rm -rf docs/retrospectives
          rm -rf docs/reflections
          rm -rf docs/shared_documents
          rm docs/project_start/analysis_design.md

      - uses: igsekor/pyspelling-any@v0.0.2
