# Check that the schedule has the right order
name: Check schedule

# Check links on the 21st day of the month.
# 21st as the first letter of this repo is the 21st letter in the alphabet.
on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 21 * *"

jobs:
  check_schedule:

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          install.packages(c("remotes", "testthat", "readr", "tibble"))
        shell: Rscript {0}

      - name: Run script
        run: ./script/check_schedule.R

