# Check that there is correct spelling in all files
name: Check spelling

on:
  push:
    paths:
      - .github/workflows/check_markdown.yaml
      - .wordlist.txt
      - .spellcheck.yml
      - '**.md'
  pull_request:
    paths:
      - .github/workflows/check_markdown.yaml
      - .wordlist.txt
      - .spellcheck.yml
      - '**.md'
  schedule:
  - cron: "0 0 16 * *"


jobs:
  check_spelling:

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:

      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Remove folders that must not be spellchecked
        run: |
          rm -rf docs/evaluations
          rm -rf docs/meeting_notes
          rm -rf development_design
          rm -rf projects
          rm -rf docs/feedback
          rm -rf docs/retrospectives
          rm -rf docs/reflections
          rm -rf docs/shared_documents

      - name: Remove files that are not to be spellchecked yet
        run: |
          rm docs/project_start/analysis_design.md
          rm docs/development_design/excercise_1_Design.md

      - uses: igsekor/pyspelling-any@v0.0.2
