# Create an MkDocs website
name: Create website

on:
  push:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: sudo apt install graphviz
      - run: pip install mkdocs-material
      - run: pip install mkdocs-graphviz
      - run: mkdocs gh-deploy --force
